### ISSUE TITLE
Agressive and Experimental mode can cause bus despawning

### ISSUE THREAD

**Issue by Leni-Vienne** [Vectorial1024/ExpressBusServices#19]
I have spotted an issue with bus stops on 3u long road. Buses will return to depot or despawn on the second time they come across a 3u stop, which makes buses quite unreliable at picking up passengers.

With this savegame below, buses on the red line will despawn but only once as I couldn't reproduce the repeating pattern like on the video. It could still be useful for testing purposes.

https://drive.google.com/file/d/1nDLBsCtM-3BnNj_MwJxX8e9HigpR1TkZ/view?usp=sharing

In the end, here are my findings :
- TLM alone with express buses setting enabled causes despawning
- TLM alone with express buses setting unchecked works just like vanilla, long stops but no despawning
- TLM + EBS mod and its TLM plugin in Aggressive and Experimental mode causes despawning
- TLM + EBS mod and its TLM plugin in Prudential mode doesn't cause despawning

I hope this have been helpful. I'm happily using prudential mode at the moment as it's still way better than vanilla ;)

**Comment by Vectorial1024** [comment]
> Experimental mode

This is supposed to be a placeholder for #9 but currently it is exactly the Aggressive mode because I currently do not know how to approach #9.

------

But still, because the Aggressive mode is based on TLM's express bus mode, at the end of the day, if we got problems with that, it be best if we also put a link on TLM's side.

(imo, it is rather rare to set a bus stop at some 3u segment, but anyway...)

**Comment by Leni-Vienne** [comment]
Thank you for mentioning the issue to Klyte, I didn't if TLM's express buses was based on your mod or not.

I agree, my use case is very specific as I'm building as 1:1 city in a mountainous area so the roads are very narrow and the nodes are often close to one another at intersections. So in spite of the use of move it and NMT's Remove Node feature, around 15 out of 20 bus lines were affected

**Comment by Vectorial1024** [comment]
Unfortunately now that Cities Skylines 2 is released and Klyte45 has moved onto CS2 modding (see Extended Transport Manager XTM), it is not possible to determine what went wrong.

What I can see is that, at the moment the bus is about to arrive at the 3u bus stop, it visually vanishes but still retains game data (eg if I opened the info view of the bus before it vanishes, I can still see its info view). At this point, it can still correctly say it wants to go to the next bus stop, and it is still assigned to a bus line. But basically, on the next calculation step, it gets cleaned up by the game and the info view disappears.

My guess is that, we are testing the very limits of the game engine by using 3u bus stops. 3u roads are normally not possible since even if I somehow disable node snapping, the shortest road segment is still 4u. Things can get weird when the distance is too close; ref the realism players utilizing the surface decals etc to cover up broken highway intersection surfaces because the game cannot correctly handle extremely-short-distance intersections, and the surface texture tears up and breaks.

Therefore, closing.
