### ISSUE TITLE
The bus doesn't start.

### ISSUE THREAD

**Issue by PC28K** [Vectorial1024/ExpressBusServices#3]
The bus doesn't start from the starting point.

When the gauge indicating the ride rate reaches its limit and then initializes, the bus must start, but the accumulation of the gauge begins again. It was only after a few repetitions of this action that the bus was able to start. I don't know if this action is intended, but I think it's the cause of the problem.

[https://www.youtube.com/watch?v=r9_HgQ6scbQ](youtube video)

IPT in use, I don't know if IPT works properly when not using it.

**Comment by Vectorial1024** [comment]
Me using TLM I don't notice any problems, since under TLM it would be the vanilla unbuncher working to make space between buses.

Under IPT, you should notice that, after the bus departs, things are working just as intended.

More info on IPT, when the bar is blue (<100%) it means it is the standard stop waiting timer. But when the bar is green (>= 100%) but the bus still do not leave, then it is usually these cases:

1. Bus unbunching
2. Some CIMs did not enter vehicle yet (e.g., 1000+ CIMs waiting at metro station, metro arrives, and some CIMs need to walk to the end of the metro to enter the metro)
3. Some error inside the waiting code that was "covered" and did not "spill out"

For now, if the waiting time is too long, maybe you can delete that bus, and then IPT spawns another replacement bus, the next bus will usually be able to leave quickly.

Another way of temporarily fixing the problem will be to check your "unbunch aggressiveness" under IPT. Before I switch from IPT to TLM, I usually set the value to 3, and buses will usually leave soon enough.

Or this may be some IPT2 custom unbuncher working to fix the "bunch" problem. Maybe, "oh look, so many buses at the stop, I should spread them out further". Just my guess.

**Comment by PC28K** [comment]
Thank you so much for explaining. I set the "unbunch aggressiveness" to 3, and all the buses started moving properly. All the buses are working right now. 

I really like the function of this mod. thank you!

**Comment by Vectorial1024** [comment]
Glad to have helped!
